# Generated by Django 5.2.5 on 2025-08-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('members', '0003_alter_members_studentnumber'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('member', 'event')},
        ),
    ]
