# Generated by Django 5.2.5 on 2025-08-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendance_unique_together"),
        ("members", "0005_alter_members_yearlevel"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="attendance",
            name="section",
            field=models.CharField(
                choices=[
                    ("morning", "Morning"),
                    ("afternoon", "Afternoon"),
                    ("night", "Night"),
                ],
                default=True,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="has_afternoon",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="has_morning",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="has_night",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("member", "event", "section")},
        ),
    ]
