# Generated by Django 5.2.5 on 2025-08-16 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNumber', models.CharField(editable=False, max_length=20, unique=True)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(blank=True, max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('yearLevel', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], max_length=1)),
                ('program', models.CharField(choices=[('BSCS', 'BS in Computer Science'), ('BSIT', 'BS in Information Technology'), ('BSIS', 'BS in Information Systems')], max_length=4)),
                ('cspcEmail', models.EmailField(max_length=254, unique=True)),
                ('contactNumber', models.CharField(blank=True, max_length=15)),
                ('position', models.CharField(choices=[('Officer', 'Officer'), ('Member', 'Member')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
    ]
