# Generated by Django 5.2.5 on 2025-08-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_members_yearlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='studentNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
