# Generated by Django 5.2.5 on 2025-08-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_members_studentnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="foodRestriction",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="members",
            name="isReg",
            field=models.CharField(
                choices=[("Regular", "Regular"), ("Irregular", "Irregular")],
                default="Regular",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="members",
            name="position",
            field=models.CharField(
                choices=[("Officer", "Officer"), ("Member", "Member")],
                default="Member",
                max_length=10,
            ),
        ),
    ]
