# Generated by Django 5.2.5 on 2025-08-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_members_foodrestriction_members_isreg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="yearLevel",
            field=models.IntegerField(choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")]),
        ),
    ]
