# Generated by Django 5.2.5 on 2025-08-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_user'),
        ('members', '0005_alter_members_yearlevel'),
    ]

    operations = [
    ]
