# Generated by Django 5.2.5 on 2025-08-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_merge_0002_members_user_0005_alter_members_yearlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='temp_password',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='members',
            name='contactNumber',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
