# Generated by Django 5.2.5 on 2025-09-06 06:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_members_temp_password_alter_members_contactnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='section',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='program',
            field=models.CharField(choices=[('BSCS', 'BS in Computer Science'), ('BSIT', 'BS in Information Technology'), ('BSIS', 'BS in Information Systems'), ('BLIS', 'BS in Library and Information Science')], max_length=4),
        ),
        migrations.AlterField(
            model_name='members',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_code'),
        ),
    ]
